// ============================================================================
// PassRegistry — the mirror table itself.  See the header for what this is
// and why it exists.  Order = GuiApp::recordFrame record order (viewer LR
// chain; the GT path in compare mode repeats the same zones, so shared zone
// names sum across paths in the editor's ms readout).
// ============================================================================
#include "gui/PassRegistry.h"

namespace sr::rg {

const std::vector<PassNode>& passTable() {
    static const std::vector<PassNode> kTable = {
        // name              zone               toggle
        // reads / writes / note
        {"shadows", "shadows", PassToggle::Shadows,
         PassToggle::None,
         {}, {"shadow map"},
         nullptr},
        {"occlusion cull", "occlusion_cull", PassToggle::Occlusion,
         PassToggle::None,
         {"hiz"}, {"draw cmds"},
         "marches the previous frame's Hi-Z"},
        {"gbuffer", "gbuffer", PassToggle::None,
         PassToggle::None,
         {"draw cmds"}, {"gbuffer", "depth", "motion"},
         "structural — cannot be disabled safely"},
        {"hiz", "hiz", PassToggle::None,
         PassToggle::None,
         {"depth"}, {"hiz"},
         "structural — feeds SSR / contact shadows / occlusion cull"},
        {"gtao", "gtao", PassToggle::None,
         PassToggle::None,
         {"depth", "gbuffer"}, {"ao"},
         "structural — depth chain + main + temporal + blur"},
        {"lighting", "lighting", PassToggle::None,
         PassToggle::None,
         {"gbuffer", "ao", "shadow map"}, {"hdr color"},
         "structural — cannot be disabled safely"},
        {"contact shadows", nullptr, PassToggle::ContactShadows,
         PassToggle::Shadows,
         {"hiz", "shadow map"}, {},
         "screen-space ray march inside the lighting pass; its cost is part of "
         "\"lighting\""},
        {"volumetric fog", "volfog", PassToggle::VolFog,
         PassToggle::None,
         {"depth", "hdr color"}, {"fog volume", "hdr color"},
         "toggling resets the temporal history"},
        {"ssr (opaque)", "reflections", PassToggle::Ssr,
         PassToggle::None,
         {"gbuffer", "hiz", "hdr color"}, {"color pyramid", "hdr color"},
         "color pyramid + trace + temporal composite — CLI/engine.toml only "
         "(--ssr); this node's checkbox is locked in the GUI"},
        {"planar reflection", "planar", PassToggle::PlanarReflection,
         PassToggle::None,
         {"shadow map"}, {"reflection color"},
         "mirrored-view GBuffer + lighting for the nearest mirror plane in view; "
         "recorded only for scenes with mirror glass (Bistro storefront), off = "
         "the panes fall back to the screen-space trace"},
        {"transparent", "transparent", PassToggle::None,
         PassToggle::None,
         {"hdr color", "depth", "color pyramid", "fog volume", "reflection color"},
         {"hdr color", "reactive mask"},
         "recorded only when the scene has alpha-blend materials"},
        {"bloom", "bloom", PassToggle::Bloom,
         PassToggle::None,
         {"hdr color"}, {"bloom pyramid"},
         nullptr},
        {"motion blur", "postfx", PassToggle::MotionBlur,
         PassToggle::None,
         {"hdr color", "depth", "motion"}, {"hdr color"},
         "shares the postfx pass (and its timing) with depth of field"},
        {"depth of field", "postfx", PassToggle::Dof,
         PassToggle::None,
         {"hdr color", "depth", "motion"}, {"hdr color"},
         "shares the postfx pass (and its timing) with motion blur"},
        {"reactive dilate", "reactive_dilate", PassToggle::None,
         PassToggle::None,
         {"reactive mask", "motion"}, {"reactive mask"},
         "recorded only when the scene has alpha-blend materials"},
        {"auto exposure", "auto_exposure", PassToggle::AutoExposure,
         PassToggle::None,
         {"hdr color"}, {"exposure"},
         nullptr},
        {"upscale", "upscale", PassToggle::None,
         PassToggle::None,
         {"hdr color", "depth", "motion", "reactive mask", "exposure"},
         {"upscaled"},
         "structural — one sub-zone per algorithm column"},
        {"gt (compare)", "gt", PassToggle::None,
         PassToggle::None,
         {"draw cmds"}, {"gt color"},
         "compare-mode reference path (repeats the LR zone names)"},
        {"metrics (compare)", "metrics", PassToggle::None,
         PassToggle::None,
         {"upscaled", "gt color"}, {},
         "compare mode only"},
        {"lens: chromatic aberration", nullptr, PassToggle::LensCa,
         PassToggle::None,
         {}, {},
         "compose-pass push constants, not a separate pass"},
        {"lens: vignette", nullptr, PassToggle::LensVignette,
         PassToggle::None,
         {}, {},
         "compose-pass push constants, not a separate pass"},
        {"lens: film grain", nullptr, PassToggle::LensGrain,
         PassToggle::None,
         {}, {},
         "compose-pass push constants, not a separate pass"},
        {"compose", "compose", PassToggle::None,
         PassToggle::None,
         {"upscaled", "gt color", "bloom pyramid"}, {"composite"},
         "structural — assembles the presented composite"},
        {"present", "present", PassToggle::None,
         PassToggle::None,
         {"composite"}, {"swapchain"},
         "structural — cannot be disabled safely"},
    };
    return kTable;
}

} // namespace sr::rg
